#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${HERMES_CURRENT_CONFIG_DIR:-$ROOT_DIR/current_config}"
ANSWERS_FILE="${HERMES_CONFIGURATION_ANSWERS:-$ROOT_DIR/configuration_answers}"
RUN_INSTALLER=true
FROM_ANSWERS=false

usage() {
  cat <<'EOF'
Create an isolated Hermes deployment configuration and optionally run install.sh.

Usage:
  ./configure.sh [--config-dir PATH] [--answers-file PATH] [--from-answers] [--no-install]

The default ./current_config directory contains hermes.env, the fully composed
bootstrap tree, and installer artifacts. The root-level configuration_answers
file stores the answers with mode 0600. Both paths are excluded from Git.

Use --from-answers to rebuild current_config after updating the repository.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config-dir)
      [[ $# -ge 2 && -n "$2" ]] || { printf 'ERROR: --config-dir requires a path.\n' >&2; exit 2; }
      CONFIG_DIR="$2"; shift 2 ;;
    --answers-file)
      [[ $# -ge 2 && -n "$2" ]] || { printf 'ERROR: --answers-file requires a path.\n' >&2; exit 2; }
      ANSWERS_FILE="$2"; shift 2 ;;
    --from-answers) FROM_ANSWERS=true; shift ;;
    --no-install) RUN_INSTALLER=false; shift ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'ERROR: unknown argument: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done
CONFIG_DIR="$(mkdir -p "$(dirname "$CONFIG_DIR")" && cd "$(dirname "$CONFIG_DIR")" && pwd)/$(basename "$CONFIG_DIR")"
ANSWERS_FILE="$(mkdir -p "$(dirname "$ANSWERS_FILE")" && cd "$(dirname "$ANSWERS_FILE")" && pwd)/$(basename "$ANSWERS_FILE")"

export HERMES_INSTALL_LIB_ONLY=true
# shellcheck source=install.sh
source "$ROOT_DIR/install.sh"
unset HERMES_INSTALL_LIB_ONLY

prompt_value() {
  local label="$1" default="${2:-}" value
  if [[ -n "$default" ]]; then
    read -r -p "$label [$default]: " value
    printf '%s' "${value:-$default}"
  else
    while true; do
      read -r -p "$label: " value
      [[ -n "$value" ]] && { printf '%s' "$value"; return; }
      printf 'A value is required.\n' >&2
    done
  fi
}

ask_yes_no() {
  local label="$1" default="$2" answer suffix
  [[ "$default" == true ]] && suffix='Y/n' || suffix='y/N'
  while true; do
    read -r -p "$label [$suffix]: " answer
    answer="${answer:-$([[ "$default" == true ]] && printf y || printf n)}"
    case "$answer" in
      y|Y|yes|YES) return 0 ;;
      n|N|no|NO) return 1 ;;
      *) printf 'Please answer yes or no.\n' >&2 ;;
    esac
  done
}

validate_hostname() {
  [[ "$1" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ && "$1" == *.* ]]
}

prompt_hostname() {
  local label="$1" default="$2" value
  while true; do
    value="$(prompt_value "$label" "$default")"
    validate_hostname "$value" && { printf '%s' "$value"; return; }
    printf 'Enter a DNS hostname such as hermes.example.com.\n' >&2
  done
}

prompt_password() {
  local first second
  while true; do
    read -r -s -p 'Dashboard/WebUI password (leave empty to generate): ' first; printf '\n' >&2
    [[ -z "$first" ]] && { printf ''; return; }
    read -r -s -p 'Confirm Dashboard/WebUI password: ' second; printf '\n' >&2
    [[ "$first" == "$second" ]] || { printf 'Passwords do not match.\n' >&2; continue; }
    if (( ${#first} < 14 )); then
      printf 'Use at least 14 characters, or leave empty for a generated password.\n' >&2
      continue
    fi
    printf '%s' "$first"
    return
  done
}

write_setting() {
  local target="$1" name="$2" value="$3"
  printf '%s=%q\n' "$name" "$value" >> "$target"
}

if [[ "$FROM_ANSWERS" == true ]]; then
  [[ -f "$ANSWERS_FILE" ]] || { printf 'ERROR: answers file not found: %s\n' "$ANSWERS_FILE" >&2; exit 1; }
  # Generated by this script, mode 0600, and Git-ignored.
  # shellcheck disable=SC1090
  source "$ANSWERS_FILE"
  printf 'Rebuilding current_config from %s\n' "$ANSWERS_FILE"
else
  printf '\nHermes Kubernetes configuration wizard\n'
  printf 'The Agent is mandatory. Optional components can be selected independently.\n\n'

  HERMES_NAMESPACE="$(prompt_value 'Kubernetes namespace' 'hermes')"
  while true; do
    printf 'Bootstrap profile:\n'
    printf '  1) personal-assistant\n'
    printf '  2) universal-system-architect\n'
    read -r -p 'Select profile [1]: ' profile_choice
    case "${profile_choice:-1}" in
      1|personal-assistant) HERMES_BOOTSTRAP_PROFILE=personal-assistant; break ;;
      2|universal-system-architect) HERMES_BOOTSTRAP_PROFILE=universal-system-architect; break ;;
      *) printf 'Choose 1 or 2.\n' >&2 ;;
    esac
  done

  MODEL_PROVIDER="$(prompt_value 'Hermes model provider' 'codex')"
  MODEL_NAME="$(prompt_value 'Hermes model' 'gpt-5.6-luna')"

  HERMES_DASHBOARD_ENABLED=false
  HERMES_WEBUI_ENABLED=false
  HERMES_BROWSER_ENABLED=false
  ask_yes_no 'Install Dashboard?' true && HERMES_DASHBOARD_ENABLED=true
  ask_yes_no 'Install WebUI?' true && HERMES_WEBUI_ENABLED=true
  ask_yes_no 'Install Browserless Chromium?' true && HERMES_BROWSER_ENABLED=true

  WEBUI_HOST=''
  DASHBOARD_HOST=''
  [[ "$HERMES_WEBUI_ENABLED" == true ]] && WEBUI_HOST="$(prompt_hostname 'WebUI hostname' 'hermes.example.com')"
  [[ "$HERMES_DASHBOARD_ENABLED" == true ]] && DASHBOARD_HOST="$(prompt_hostname 'Dashboard hostname' 'hermes-admin.example.com')"

  DASHBOARD_AUTH_USER=''
  DASHBOARD_AUTH_PASSWORD=''
  if [[ "$HERMES_DASHBOARD_ENABLED" == true || "$HERMES_WEBUI_ENABLED" == true ]]; then
    if [[ "$HERMES_DASHBOARD_ENABLED" == true ]]; then
      DASHBOARD_AUTH_USER="$(prompt_value 'Dashboard username' 'admin')"
      [[ "$DASHBOARD_AUTH_USER" =~ ^[A-Za-z0-9._-]+$ ]] || { printf 'ERROR: invalid Dashboard username.\n' >&2; exit 1; }
    else
      DASHBOARD_AUTH_USER=admin
    fi
    DASHBOARD_AUTH_PASSWORD="$(prompt_password)"
  fi

  HERMES_ANSIBLE_SETUP=false
  HERMES_ANSIBLE_VERSION=''
  HERMES_SSH_SETUP=false
  if ask_yes_no 'Install and configure Ansible?' false; then
    HERMES_ANSIBLE_SETUP=true
    while true; do
      HERMES_ANSIBLE_VERSION="$(prompt_value 'Ansible package version' '14.1.0')"
      [[ "$HERMES_ANSIBLE_VERSION" =~ ^[0-9]+([.][0-9]+){1,2}$ ]] && break
      printf 'Enter a package version such as 14.1.0.\n' >&2
    done
    HERMES_SSH_SETUP=true
    printf 'SSH key setup enabled because Ansible was selected.\n'
  else
    ask_yes_no 'Prepare a persistent SSH keypair?' false && HERMES_SSH_SETUP=true
  fi

  if ask_yes_no 'Overwrite existing bootstrap-managed files on the PVC?' false; then
    HERMES_BOOTSTRAP_MODE=overwrite
  else
    HERMES_BOOTSTRAP_MODE=missing
  fi
fi

: "${HERMES_NAMESPACE:?missing HERMES_NAMESPACE in answers}"
: "${HERMES_BOOTSTRAP_PROFILE:?missing HERMES_BOOTSTRAP_PROFILE in answers}"
: "${HERMES_DASHBOARD_ENABLED:?missing HERMES_DASHBOARD_ENABLED in answers}"
: "${HERMES_WEBUI_ENABLED:?missing HERMES_WEBUI_ENABLED in answers}"
: "${HERMES_BROWSER_ENABLED:?missing HERMES_BROWSER_ENABLED in answers}"
: "${HERMES_ANSIBLE_SETUP:?missing HERMES_ANSIBLE_SETUP in answers}"
: "${HERMES_SSH_SETUP:?missing HERMES_SSH_SETUP in answers}"
: "${HERMES_BOOTSTRAP_MODE:?missing HERMES_BOOTSTRAP_MODE in answers}"
WEBUI_HOST="${WEBUI_HOST:-}"
DASHBOARD_HOST="${DASHBOARD_HOST:-}"
DASHBOARD_AUTH_USER="${DASHBOARD_AUTH_USER:-}"
DASHBOARD_AUTH_PASSWORD="${DASHBOARD_AUTH_PASSWORD:-}"
HERMES_ANSIBLE_VERSION="${HERMES_ANSIBLE_VERSION:-}"
MODEL_PROVIDER="${MODEL_PROVIDER:-codex}"
MODEL_NAME="${MODEL_NAME:-gpt-5.6-luna}"
[[ "$MODEL_PROVIDER" =~ ^[A-Za-z0-9._:/-]+$ ]] || { printf 'ERROR: invalid model provider.\n' >&2; exit 1; }
[[ "$MODEL_NAME" =~ ^[A-Za-z0-9._:/-]+$ ]] || { printf 'ERROR: invalid model name.\n' >&2; exit 1; }
[[ "$HERMES_BOOTSTRAP_MODE" == missing || "$HERMES_BOOTSTRAP_MODE" == overwrite ]] || { printf 'ERROR: invalid bootstrap mode in answers.\n' >&2; exit 1; }
if [[ "$HERMES_ANSIBLE_SETUP" == true ]]; then
  [[ "$HERMES_ANSIBLE_VERSION" =~ ^[0-9]+([.][0-9]+){1,2}$ ]] || { printf 'ERROR: invalid Ansible version in answers.\n' >&2; exit 1; }
  HERMES_SSH_SETUP=true
fi

CONFIG_MARKER="$CONFIG_DIR/.hermes-current-config"
if [[ -e "$CONFIG_DIR" && -n "$(find "$CONFIG_DIR" -mindepth 1 -print -quit 2>/dev/null)" ]]; then
  if [[ "$FROM_ANSWERS" == true ]]; then
    [[ -f "$CONFIG_MARKER" ]] || {
      printf 'ERROR: refusing to replace unowned directory without %s\n' "$CONFIG_MARKER" >&2
      exit 1
    }
    rm -rf "$CONFIG_DIR"
  else
    ask_yes_no "Replace existing configuration in $CONFIG_DIR?" false || { printf 'Configuration cancelled.\n'; exit 0; }
    rm -rf "$CONFIG_DIR"
  fi
fi
mkdir -p "$CONFIG_DIR/artifacts" "$CONFIG_DIR/bootstrap"
chmod 700 "$CONFIG_DIR" "$CONFIG_DIR/artifacts" "$CONFIG_DIR/bootstrap"
: > "$CONFIG_MARKER"
chmod 600 "$CONFIG_MARKER"

# Reuse canonical profile composition so setup cannot drift from install.sh.
RENDER_DIR="$CONFIG_DIR/artifacts"
export HERMES_BOOTSTRAP_PROFILE HERMES_ANSIBLE_SETUP HERMES_SSH_SETUP
compose_profile_bootstrap "$HERMES_BOOTSTRAP_PROFILE"
cp -a "$HERMES_BOOTSTRAP_DIR"/. "$CONFIG_DIR/bootstrap"/
rm -rf "$RENDER_DIR/bootstrap-profile"
HERMES_BOOTSTRAP_DIR="$CONFIG_DIR/bootstrap"
HERMES_RENDER_DIR="$CONFIG_DIR/artifacts"

# Deliver Agent-native configuration through the existing bootstrap path to the
# persistent /opt/data/config.yaml file.
cat > "$HERMES_BOOTSTRAP_DIR/config.yaml" <<EOF
provider: $MODEL_PROVIDER
model: $MODEL_NAME
agent:
  verify_on_stop: false
terminal:
  cwd: /workspace
display:
  tool_progress: all
gateway:
  host: 0.0.0.0
  port: 8642
EOF
chmod 600 "$HERMES_BOOTSTRAP_DIR/config.yaml"

ENV_OUT="$CONFIG_DIR/hermes.env"
umask 077
: > "$ENV_OUT"
write_setting "$ENV_OUT" HERMES_NAMESPACE "$HERMES_NAMESPACE"
write_setting "$ENV_OUT" HERMES_AGENT_ENABLED true
write_setting "$ENV_OUT" HERMES_DASHBOARD_ENABLED "$HERMES_DASHBOARD_ENABLED"
write_setting "$ENV_OUT" HERMES_WEBUI_ENABLED "$HERMES_WEBUI_ENABLED"
write_setting "$ENV_OUT" HERMES_BROWSER_ENABLED "$HERMES_BROWSER_ENABLED"
write_setting "$ENV_OUT" WEBUI_HOST "$WEBUI_HOST"
write_setting "$ENV_OUT" DASHBOARD_HOST "$DASHBOARD_HOST"
write_setting "$ENV_OUT" DASHBOARD_AUTH_USER "$DASHBOARD_AUTH_USER"
write_setting "$ENV_OUT" DASHBOARD_AUTH_PASSWORD "$DASHBOARD_AUTH_PASSWORD"
write_setting "$ENV_OUT" MODEL_PROVIDER "$MODEL_PROVIDER"
write_setting "$ENV_OUT" MODEL_NAME "$MODEL_NAME"
write_setting "$ENV_OUT" HERMES_BOOTSTRAP_PROFILE "$HERMES_BOOTSTRAP_PROFILE"
write_setting "$ENV_OUT" HERMES_BOOTSTRAP_DIR "$HERMES_BOOTSTRAP_DIR"
write_setting "$ENV_OUT" HERMES_BOOTSTRAP_MODE "$HERMES_BOOTSTRAP_MODE"
write_setting "$ENV_OUT" HERMES_RENDER_DIR "$HERMES_RENDER_DIR"
write_setting "$ENV_OUT" HERMES_ANSIBLE_SETUP "$HERMES_ANSIBLE_SETUP"
write_setting "$ENV_OUT" HERMES_ANSIBLE_VERSION "$HERMES_ANSIBLE_VERSION"
write_setting "$ENV_OUT" HERMES_SSH_SETUP "$HERMES_SSH_SETUP"
write_setting "$ENV_OUT" HERMES_SSH_GENERATE_KEY "$HERMES_SSH_SETUP"
chmod 600 "$ENV_OUT"

if [[ "$FROM_ANSWERS" != true ]]; then
  : > "$ANSWERS_FILE"
  write_setting "$ANSWERS_FILE" HERMES_NAMESPACE "$HERMES_NAMESPACE"
  write_setting "$ANSWERS_FILE" HERMES_BOOTSTRAP_PROFILE "$HERMES_BOOTSTRAP_PROFILE"
  write_setting "$ANSWERS_FILE" HERMES_DASHBOARD_ENABLED "$HERMES_DASHBOARD_ENABLED"
  write_setting "$ANSWERS_FILE" HERMES_WEBUI_ENABLED "$HERMES_WEBUI_ENABLED"
  write_setting "$ANSWERS_FILE" HERMES_BROWSER_ENABLED "$HERMES_BROWSER_ENABLED"
  write_setting "$ANSWERS_FILE" WEBUI_HOST "$WEBUI_HOST"
  write_setting "$ANSWERS_FILE" DASHBOARD_HOST "$DASHBOARD_HOST"
  write_setting "$ANSWERS_FILE" DASHBOARD_AUTH_USER "$DASHBOARD_AUTH_USER"
  write_setting "$ANSWERS_FILE" DASHBOARD_AUTH_PASSWORD "$DASHBOARD_AUTH_PASSWORD"
  write_setting "$ANSWERS_FILE" MODEL_PROVIDER "$MODEL_PROVIDER"
  write_setting "$ANSWERS_FILE" MODEL_NAME "$MODEL_NAME"
  write_setting "$ANSWERS_FILE" HERMES_ANSIBLE_SETUP "$HERMES_ANSIBLE_SETUP"
  write_setting "$ANSWERS_FILE" HERMES_ANSIBLE_VERSION "$HERMES_ANSIBLE_VERSION"
  write_setting "$ANSWERS_FILE" HERMES_SSH_SETUP "$HERMES_SSH_SETUP"
  write_setting "$ANSWERS_FILE" HERMES_BOOTSTRAP_MODE "$HERMES_BOOTSTRAP_MODE"
  chmod 600 "$ANSWERS_FILE"
fi

printf '\nConfiguration created.\n'
printf '  Directory:  %s\n' "$CONFIG_DIR"
printf '  Environment: %s (mode 600)\n' "$ENV_OUT"
printf '  Bootstrap:   %s (%s mode)\n' "$HERMES_BOOTSTRAP_DIR" "$HERMES_BOOTSTRAP_MODE"
printf '  Agent config: %s -> /opt/data/config.yaml\n' "$HERMES_BOOTSTRAP_DIR/config.yaml"
printf '  Artifacts:   %s\n' "$HERMES_RENDER_DIR"
printf '  Answers:     %s (mode 600)\n' "$ANSWERS_FILE"
printf '  Components:  agent%s%s%s\n' \
  "$([[ "$HERMES_DASHBOARD_ENABLED" == true ]] && printf ', dashboard')" \
  "$([[ "$HERMES_WEBUI_ENABLED" == true ]] && printf ', webui')" \
  "$([[ "$HERMES_BROWSER_ENABLED" == true ]] && printf ', browser')"
printf '  Ansible:     %s%s\n' "$HERMES_ANSIBLE_SETUP" "$([[ "$HERMES_ANSIBLE_SETUP" == true ]] && printf ' (%s)' "$HERMES_ANSIBLE_VERSION")"
printf '  SSH keys:    %s\n\n' "$HERMES_SSH_SETUP"

installer_cmd="HERMES_INSTALL_LIB_ONLY=false ENV_FILE=$(printf '%q' "$ENV_OUT") $(printf '%q' "$ROOT_DIR/install.sh")"
if [[ "$RUN_INSTALLER" == true ]] && ask_yes_no 'Run install.sh now?' false; then
  HERMES_INSTALL_LIB_ONLY=false ENV_FILE="$ENV_OUT" "$ROOT_DIR/install.sh"
else
  printf 'Run the installer with:\n  %s\n' "$installer_cmd"
fi
